telephones: []
email: admin@asil-impro.fr
facebook: https://www.facebook.com/profile.php?id=100063601480001
instagram: https://www.instagram.com/asil_impro/
heroTitre: "L'asso stéphanoise qui improvise depuis 22 ans !"
heroSousTitre: "Ateliers stéphanois d'improvisation loufoque"
heroImage: null
photoRejoindre: null
photoAsil: null
photoAteliers: null
photoStages: null
photoContact: null
